name: Deploy Laravel API to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Deploy to CPANEL
        uses: appleboy/scp-action@master
        env:
          TERM: xterm  
        with:
          host: dodap.ca
          username: zdn69wo5iwc8
          password: West40$Build+%
          port: 22
          source: .
          target: /home/zdn69wo5iwc8/public_html/admin.dodap.ca
