name: Deploy Laravel API to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Clear Cache Optimize
        run: php artisan optimize

      - name: Migrate
        run: php artisan migrate --force

      - name: Deploy to Hostinger
        uses: appleboy/scp-action@master
        with:
          host: 217.21.94.205
          username: u790439483
          password: Rammandir@2021
          port: 65002
          source: .
          target: domains/backlsh.com/public_html/dodap

      - name: Run php artisan optimize on Hostinger
        run: sshpass -p 'Rammandir@2021' ssh -o StrictHostKeyChecking=no u790439483@217.21.94.205 -p 65002 'cd domains/backlsh.com/public_html/dodap && php artisan optimize'
